localisation:
    ros__parameters:
        update_frequency: 50.0

local_planner:
    ros__parameters:
        update_frequency: 10.0
        car_width: 2.0
        centreofgravity_to_frontaxle: 1.483
        frame_id: "base_link"
        cruise_velocity: 8.0
        avoid_velocity: 7.0
        max_lateral_accel: 5.0
        min_curvature: 0.015
        curvature_lookahead: 120
        curvature_smooth_window: 7
        accel_rate: 4.0
        decel_rate: 6.0

global_planner:
    ros__parameters:
        update_frequency: 2.0
        waypoints_ahead: 3
        waypoints_behind: 2
        passed_threshold: 0.25
        centreofgravity_to_frontaxle: 1.483

path_tracker:
    ros__parameters:
        update_frequency: 50.0
        centreofgravity_to_frontaxle: 1.483
        wheelbase: 2.966
        lookahead_gain: 0.55
        lookahead_min: 2.8
        lookahead_max: 11.0
        closest_search_ahead: 100
        steering_limits: 0.95
        steering_rate_limit: 3.0
        velocity_gain: 1.0
