import os
import subprocess

from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch_ros.actions import Node
from launch_ros.parameter_descriptions import ParameterValue
from launch.conditions import LaunchConfigurationEquals
from launch.substitutions import LaunchConfiguration
from launch.actions import DeclareLaunchArgument, ExecuteProcess, SetEnvironmentVariable


def generate_launch_description():

    navpkg = 'autocar_nav'
    gzpkg = 'autocar_gazebo'
    descpkg = 'autocar_description'
    mappkg = 'autocar_map'

    world = os.path.join(get_package_share_directory(gzpkg), 'worlds', 'race_circuit.world')
    urdf = os.path.join(get_package_share_directory(descpkg), 'urdf', 'autocar.xacro')
    rviz = os.path.join(get_package_share_directory(descpkg), 'rviz', 'view.rviz')

    navconfig = os.path.join(get_package_share_directory(navpkg), 'config', 'navigation_params.yaml')

    use_sim_time = LaunchConfiguration('use_sim_time', default='True')

    # Experiment dimensions. Every CSV row carries these so runs are
    # comparable across sessions.
    controller = LaunchConfiguration('controller')
    profile = LaunchConfiguration('profile')
    latency_ms = LaunchConfiguration('latency_ms')
    odom_noise_std = LaunchConfiguration('odom_noise_std')
    line = LaunchConfiguration('line')
    waypoints_file = LaunchConfiguration('waypoints_file')

    subprocess.run(['killall', 'gzserver'])
    subprocess.run(['killall', 'gzclient'])

    return LaunchDescription([
        SetEnvironmentVariable('RCUTILS_CONSOLE_OUTPUT_FORMAT', '[{severity}]: {message}'),
        SetEnvironmentVariable('RCUTILS_COLORIZED_OUTPUT', '1'),

        DeclareLaunchArgument(
            'use_sim_time',
            default_value='true',
            description='Use simulation (Gazebo) clock if true. MUST stay true: '
                        'Gazebo publishes wheel TFs in sim_time, so every TF '
                        'producer/consumer has to agree, otherwise RViz drops '
                        'wheel transforms as stale and the car loses its wheels.'
        ),

        DeclareLaunchArgument(
            'controller', default_value='stanley',
            description='Controller algorithm name. Recognised values: '
                        '"stanley" (existing tracker.py) or "pure_pursuit". '
                        'Selects which node is launched AND is recorded in the CSV.'
        ),
        DeclareLaunchArgument(
            'profile', default_value='default',
            description='Tuning profile label (default | conservative | balanced | aggressive). '
                        'Recorded in the metrics CSV.'
        ),
        DeclareLaunchArgument(
            'latency_ms', default_value='0',
            description='Artificial perception->command latency in ms. 0 = off. '
                        'Recorded in the metrics CSV.'
        ),
        DeclareLaunchArgument(
            'odom_noise_std', default_value='0.0',
            description='Std dev of additive Gaussian noise on /autocar/state2D. '
                        '0.0 = off. Recorded in the metrics CSV.'
        ),

        DeclareLaunchArgument(
            'line', default_value='centerline',
            description='Path to follow: "centerline" (waypoints.csv) or '
                        '"racing" (waypoints_racing.csv, generated by '
                        'scripts/generate_racing_line.py). Selects which '
                        'CSV the global_planner loads.'
        ),

        ExecuteProcess(
            # libgazebo_ros_init.so MUST be loaded so Gazebo publishes /clock.
            # Without it, every node with use_sim_time=true hangs waiting for
            # sim time and nothing moves -- the tracker never sends cmd_vel.
            cmd=['gzserver', '--verbose', world,
                 '-s', 'libgazebo_ros_init.so',
                 '-s', 'libgazebo_ros_factory.so'],
        ),

        ExecuteProcess(
            cmd=['gzclient'],
        ),

        Node(
            package='robot_state_publisher',
            name='robot_state_publisher',
            executable='robot_state_publisher',
            output={'both': 'log'},
            parameters=[{'use_sim_time': use_sim_time}],
            arguments=[urdf]
        ),

        Node(
            package='rviz2',
            executable='rviz2',
            name='rviz2',
            arguments=['-d', rviz],
            parameters=[{'use_sim_time': use_sim_time}],
            output={'both': 'log'}
        ),

        # Localisation publishes state on /autocar/state2D_raw; the
        # latency_injector below republishes to /autocar/state2D after a
        # configurable delay (pass-through when latency_ms=0). All
        # consumers stay subscribed to /autocar/state2D unchanged.
        Node(
            package=navpkg, name='localisation', executable='localisation.py',
            parameters=[navconfig, {'use_sim_time': use_sim_time}],
            remappings=[('/autocar/state2D', '/autocar/state2D_raw')],
        ),
        Node(
            package=navpkg, name='latency_injector', executable='latency_injector.py',
            parameters=[{
                'use_sim_time': use_sim_time,
                'latency_ms': ParameterValue(latency_ms, value_type=int),
            }],
        ),
        # Global planner: same node twice, the launch arg `line` picks
        # which waypoints CSV gets loaded. Only one fires per launch.
        Node(
            package=navpkg, name='global_planner', executable='globalplanner.py',
            parameters=[navconfig, {'use_sim_time': use_sim_time,
                                    'waypoints_file': 'waypoints.csv'}],
            condition=LaunchConfigurationEquals('line', 'centerline'),
        ),
        Node(
            package=navpkg, name='global_planner', executable='globalplanner.py',
            parameters=[navconfig, {'use_sim_time': use_sim_time,
                                    'waypoints_file': 'waypoints_racing.csv'}],
            condition=LaunchConfigurationEquals('line', 'racing'),
        ),
        Node(package=navpkg, name='local_planner',  executable='localplanner.py',  parameters=[navconfig, {'use_sim_time': use_sim_time}]),
        Node(package=mappkg, name='bof',            executable='bof',              parameters=[{'use_sim_time': use_sim_time}]),
        # Controller selection: exactly one of these two starts, picked by
        # the `controller:=` launch argument. Both publish the same topics
        # (cmd_vel, lateral_error, lateral_ref) so downstream nodes don't
        # care which controller is running.
        Node(
            package=navpkg, name='path_tracker', executable='tracker.py',
            parameters=[navconfig, {'use_sim_time': use_sim_time}],
            condition=LaunchConfigurationEquals('controller', 'stanley'),
        ),
        Node(
            package=navpkg, name='path_tracker', executable='pure_pursuit.py',
            parameters=[navconfig, {'use_sim_time': use_sim_time}],
            condition=LaunchConfigurationEquals('controller', 'pure_pursuit'),
        ),
        Node(
            package=navpkg, name='lap_timer', executable='lap_timer.py',
            parameters=[{
                'use_sim_time': use_sim_time,
                'controller': ParameterValue(controller, value_type=str),
                'profile': ParameterValue(profile, value_type=str),
                'latency_ms': ParameterValue(latency_ms, value_type=int),
                'odom_noise_std': ParameterValue(odom_noise_std, value_type=float),
            }],
        ),
    ])


def main():
    generate_launch_description()


if __name__ == '__main__':
    main()
